package test;

import model.Note;
import model.NoteBuilder;
import model.NoteBuilderIntelliJ;

import java.time.LocalDate;

public class Main
{
    public static void main(String[] args)
    {
        //practice using our builder
        Note note = new NoteBuilder()
            .body("Game of thrones ended badly")
            .author("Josh Archer")
            .buildWithDefaults();

        System.out.println(note);

        //practice using a preexisting builder
        String message = new StringBuilder()
            .append("Hello")
            .append(" ")
            .append("world")
            .append("!")
            .toString();
        System.out.println(message);

        System.out.println("Hello" + " " + "world" + "!");

        //practice with a builder generated by IntelliJ
        Note another = new NoteBuilderIntelliJ()
            .setBody("Dumbledore was wronged...")
            .setAuthor("Me")
            .createNote();
    }
}
